"""Central default settings for the lightweight MRF pipeline."""

IMG_SHAPE = (96, 96)
N_COILS = 4
N_TR = 500
SUBSPACE_RANK = 5

N_ITER = 2
LAMBDA_LLR = 1e-4
STEP_SIZE = 1e-3
PATCH_SHAPE = (8, 8)
CENTER_WIDTH = 24
CALIB_WIDTH = 24

SPIRAL_FOV = 96e-3
SPIRAL_RES = 1e-3
SPIRAL_READOUT_TIME = 7e-3
SPIRAL_UNDERSAMPLE_CENTER = 12
SPIRAL_UNDERSAMPLE_EDGE = 24
SPIRAL_ADC_RATE = 1e6
TINY_GOLDEN_ANGLE = 23.63

EPG_NUM_STATES = 200
NOISE_LEVEL = 0.25
RANDOM_SEED = 42
